### ISSUE TITLE
closeLoot Bug

### ISSUE THREAD

**Issue by nikohd12** [coccoinomane/crabada.py#11]
Hi Cocco,

As part of the loot testing [here](https://github.com/coccoinomane/crabada.py/issues/10), closeLoots function isn't working.

`src.common.logger - INFO - No loots to close for user XXXXXXXXX`

Maybe it is related to the bug you mentioned where it uses the miner's logic?

**Comment by coccoinomane** [comment]
Hey @nikohd12 , thanks for reporting this issue!
Do you always get the error, even 3 hours after the mine was attacked?

The issue is probably in the [`mineIsSettled` function](https://github.com/coccoinomane/crabada.py/blob/master/src/helpers/mines.py#L28-L37) which checks whether a loot is ready to be settled or not.

**Comment by nikohd12** [comment]
> 

Hi @coccoinomane,

I was testing closeLoot as soon as my loot can be settle 10 seconds before and/or after the looting is finished.

**Comment by EugeneTeu** [comment]
i think the bug is from the api. related to the `status: open` bug with `looter_address`

**Comment by coccoinomane** [comment]
Hey @EugeneTeu , could you please elaborate on the bug? Are you referring to [these lines](https://github.com/coccoinomane/crabada.py/blob/master/src/bot/looting/closeLoots.py#L27-L29)?

Cheers,
Cocco

**Comment by EugeneTeu** [comment]
> Hey @EugeneTeu , could you please elaborate on the bug? Are you referring to [these lines](https://github.com/coccoinomane/crabada.py/blob/master/src/bot/looting/closeLoots.py#L27-L29)?
> 
> Cheers, Cocco

yea, the endpoint doesnt seem to return the mines correctly e.g open status and belong to user. not sure if its fixed alrdy.

**Comment by coccoinomane** [comment]
Hi guys,

I finally managed to tackle the issues and in the process I made the `closeLoots` script much more efficient.

In particular, we have a new function `mineCanBeSettled()` which can be used  to determine whether a mine is ready to be settled. This was not obvious to implement, because a series of conditions had to be checked.

I have pushed a new branch [`2022-03-29_fix-close-loots`](https://github.com/coccoinomane/crabada.py/tree/2022-03-29_fix-close-loots) with the new logic, would you mind giving a try?

Let me know if you find more bugs! 

Cheers,
Cocco

**Comment by loayei** [comment]
> Hi guys,
> 
> I finally managed to tackle the issues and in the process I made the `closeLoots` script much more efficient.
> 
> In particular, we have a new function `mineCanBeSettled()` which can be used to determine whether a mine is ready to be settled. This was not obvious to implement, because a series of conditions had to be checked.
> 
> I have pushed a new branch [`2022-03-29_fix-close-loots`](https://github.com/coccoinomane/crabada.py/tree/2022-03-29_fix-close-loots) with the new logic, would you mind giving a try?
> 
> Let me know if you find more bugs!
> 
> Cheers, Cocco

Can confirm closeLoots completely works now!

**Comment by coccoinomane** [comment]
Thank you for the update @loayei !

@nikohd12 I'll close the issue for now, let me know if you encounter more issues :-)

**Comment by nikohd12** [comment]
> Thank you for the update @loayei !
> 
> I have merged the branch with master.
> 
> @nikohd12 I'll close the issue for now, let me know if you encounter more issues :-)

Thank you! I have yet to test it again as I am solely mining and testing the reinforce own crab (which is working)
