### ISSUE TITLE
Advanced reinforcement strategy for HighestMP

### ISSUE THREAD

**Issue by mertf** [coccoinomane/crabada.py#35]
If HighestMP is chosen, it might be best to come up with a calculated strategy if it looks like the looter's BP will be higher than ours in the last attack. Otherwise, the bot chooses a crab with highest MP regardless of the BP comparison, and the mine is automatically lost if our BP is lower than the looter's.

**Comment by mertf** [comment]
For some reason, my mind went blank on me, and I disregarded the already-known information (BP could be lower than the looter's BP) about the MR when mining. I am closing this issue as it is not an issue at all.

**Comment by coccoinomane** [comment]
Haha no worries @mertf ! Any suggestion is welcome.

The best scenario would be to assess whether the miner can win.
If so, then the strategy can aim at a high BP crab, even a legendary one if available.
Otherwise, the highest MP crab is best because of miner's revenge.

This is something to think about for the future, especially if the number of legendary crabs increases compared to the total population.
